### ISSUE TITLE
New release to include a bump to httpx 0.23.0

### ISSUE THREAD

**Issue by dzyubam** [twonote/solid-file-python#32]
Thank you for your hard work!

Would it be possible to make a new release on PyPi so that the bump of httpx from https://github.com/twonote/solid-file-python/pull/29 would make it to the version released on PyPi?

Thank you!

**Comment by peter0083** [comment]
any thoughts @hrchu ?

**Comment by hrchu** [comment]
@dzyubam I'll check it out this week

**Comment by hrchu** [comment]
@peter0083 I've freezed [v0.2.1](https://github.com/twonote/solid-file-python/releases/tag/v0.2.1), could you publish it on PyPI?  You already have the maintainer's permission last year. Check out the procedure here: https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives

**Comment by peter0083** [comment]
@hrchu will do

**Comment by peter0083** [comment]
@hrchu thanks for the merge

@dzyubam thanks for the wait.  The new release is now up on PyPi: https://pypi.org/project/solid-file/0.2.1/

**Comment by peter0083** [comment]
If everything is good, please give me a thumbs-up and I will close the issue. 😄

**Comment by dzyubam** [comment]
Thanks a lot for your help!
