### ISSUE TITLE
Unable to login due to 302 "error"; further due to httpx version

### ISSUE THREAD

**Issue by renyuneyun** [twonote/solid-file-python#36]
We are trying to use the solid-file-python library. We noticed that it will result in "302 error" when trying to log-in to, e.g., https://solidcommunity.net.

After further investigation, v0.1.1 of solid-file-python library does not have this issue. And we found the cause: httpx library v0.18.2 does not raise errors for redirection, but recent versions raise.

This commit https://github.com/twonote/solid-file-python/commit/3b2a0bf4df9d159ec76ae0606a684746bf23c7c2 updated the dependency version, by a bot.

**Comment by peter0083** [comment]
Thank you for flagging this issue. Looks like it is related to #35 with `httpx` library getting a version bump. Any thoughts @hrchu ?

**Comment by hrchu** [comment]
Fixed in #39
